name: Build Docker Image

on:
  workflow_call:
    inputs:
      build-args:
        type: string
      dry-run:
        type: boolean
        default: false
    secrets:
      DOCKER_PASSWORD:
        required: true

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      link-tag: ${{ steps.get-tag.outputs.link-tag }}
    steps:
      - name: Cleanup the build folder
        if: ${{ !inputs.dry-run }}
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get Tag
        id: get-tag
        run: |
          echo "DOCKERHUB_REPO=$GITHUB_REPOSITORY" >> $GITHUB_ENV
          
          if [[ $GITHUB_REF_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Release tag found"
            echo "TAGS=$GITHUB_REPOSITORY:latest,$GITHUB_REPOSITORY:$GITHUB_REF_NAME" >> $GITHUB_ENV
            LINK_TAG=latest
          elif [[ $GITHUB_REF_NAME == develop ]]; then
            echo "Develop tag found"
            echo "TAGS=$GITHUB_REPOSITORY:$GITHUB_REF_NAME-latest,$GITHUB_REPOSITORY:${GITHUB_SHA:0:7}" >> $GITHUB_ENV
            LINK_TAG=${GITHUB_SHA:0:7}        
          else
            echo "Feature tag/branch found"
            echo "TAGS=$GITHUB_REPOSITORY:${GITHUB_SHA:0:7}" >> $GITHUB_ENV
            LINK_TAG=${GITHUB_SHA:0:7}
          fi
          echo "LINK_TAG=$LINK_TAG" >> $GITHUB_ENV
          echo "link-tag=$LINK_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ !inputs.dry-run }}
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.DOCKERHUB_REPO }}

      - name: Build and push (optional) Docker image
        id: build_and_push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: ${{ !inputs.dry-run }}
          tags: ${{ env.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}

      - name: Print summary
        if: ${{ !inputs.dry-run }}
        run: |
          echo '### The image repo tags:' >> $GITHUB_STEP_SUMMARY
          echo '['${{ env.DOCKERHUB_REPO }}'](https://hub.docker.com/repository/docker/'${{ env.DOCKERHUB_REPO }}'/tags/)' >> $GITHUB_STEP_SUMMARY
          echo '### The built image content:' >> $GITHUB_STEP_SUMMARY
          echo '['${{ env.DOCKERHUB_REPO }}':'${{ env.LINK_TAG }}'](https://hub.docker.com/layers/'${{ env.DOCKERHUB_REPO }}'/'${{ env.LINK_TAG }}'/images/'${{ steps.build_and_push.outputs.digest }}')' >> $GITHUB_STEP_SUMMARY
          echo 'Output Tag: '${{ steps.get-tag.outputs.link-tag }}'' >> $GITHUB_STEP_SUMMARY
          
