name: Deploy Docker Image

on:
  workflow_call:
    inputs:
      link-tag:
        type: string
        required: true
      gitops-file:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  deploy-image:
    name: Update GitOps values file
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update GitOps file and release tag
        run: |
          echo "Updating GitOps file: ${{ inputs.gitops-file }}"
          echo "image: $GITHUB_REPOSITORY" > "${{ inputs.gitops-file }}"
          echo "tag: ${{ inputs.link-tag }}" >> "${{ inputs.gitops-file }}"          
          echo "app: ${GITHUB_REPOSITORY##*/}" >> "${{ inputs.gitops-file }}"
          git add "${{ inputs.gitops-file }}"
          git fetch origin --tags ${{ github.ref_name }}
          git merge origin/${{ github.ref_name }}
          git commit -m "github-actions[bot] deployed image $GITHUB_REPOSITORY:${{ inputs.link-tag }} to ${{ inputs.environment }}" || echo "No changes to commit"
          if [[ ${{ inputs.environment }} == 'preprod' ]]; then
            if git rev-parse "${{ inputs.link-tag }}" >/dev/null 2>&1; then
              echo "Tag '${{ inputs.link-tag }}' already exists. Exiting."
              exit 1
            fi
            git tag "${{ inputs.link-tag }}"
            git push || echo "No changes to push"
            git push origin "${{ inputs.link-tag }}" || echo "No tags to push tag"          
          fi
          git push || echo "No changes to push"
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Print summary
        if: always()
        run: |
          echo '### CD Action:' >> $GITHUB_STEP_SUMMARY
            echo "Pushed image $GITHUB_REPOSITORY:${{ inputs.link-tag }} to ${{ inputs.environment }}" GitOps>> $GITHUB_STEP_SUMMARY
            echo "[View Commit](https://github.com/$GITHUB_REPOSITORY/commit/$COMMIT_SHA)" >> $GITHUB_STEP_SUMMARY
