name: Deploy Docker Image

on:
  workflow_call:
    inputs:
      link-tag:
        type: string
        required: true
      gitops-file:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  deploy-image:
    name: Update GitOps values file
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update GitOps file
        run: |
          echo "Updating GitOps file: ${{ inputs.gitops-file }}"
          echo "tag: ${{ inputs.link-tag }}" >> "${{ inputs.gitops-file }}"
          git add "${{ inputs.gitops-file }}"
          git commit -m "github-actions[bot] deployed image $GITHUB_REPOSITORY:${{ inputs.link-tag }} to ${{ inputs.environment }}"
          git push

      - name: Print summary
        if: always()
        run: |
          echo '### CD Action:' >> $GITHUB_STEP_SUMMARY
            echo "Deployed image $GITHUB_REPOSITORY:${{ inputs.link-tag }} to ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
