name: Publish Docker Image

on:
  workflow_call:

jobs:
  quality-check:
    name: Code Quality Gates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # --- LINT CHECK ---
      - name: Lint code (ESLint)
        run: npx eslint .

      # --- UNIT TESTS + COVERAGE ---
      - name: Run tests with coverage (Jest)
        run: npm run test -- --coverage

      - name: Check test coverage threshold
        run: |
          COVERAGE=$(npx jest --coverage --coverageReporters=text-summary | grep 'All files' | awk '{print $3}' | tr -d '%')
          echo "Current coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Coverage below threshold (80%)"
            exit 1
          fi

      # --- FORMAT CHECK ---
      - name: Check formatting (Prettier)
        run: npm run format:check