name: Dev CI/CD

on:
  workflow_call:
    inputs:
      deploy-to-environment:
        required: true
        type: string
        description: 'Environment to deploy to'

jobs:
  action-based-ci:
    if: startsWith(github.head_ref || github.ref_name, 'feature/') || github.ref_name == 'main '&& github.ref_type == 'branch'
    name: Action-Based CI Workflow
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.get-image-tags.outputs.new-tag }}
      new-image: ${{ steps.get-image-tags.outputs.new-image }}
      start-time: ${{ steps.ci-preflight.outputs.start-time }}
      gitops-repo: ${{ steps.ci-preflight.outputs.gitops-repo }}
      gitops-file: ${{ steps.ci-preflight.outputs.gitops-file }}
      app-name: ${{ steps.ci-preflight.outputs.app-name }}
      target-namespace: ${{ steps.ci-preflight.outputs.target-namespace }}
      subdomain: ${{ steps.ci-preflight.outputs.subdomain }}
      public-service-fqdn: ${{ steps.ci-preflight.outputs.public-service-fqdn }}
      local-service-fqdn: ${{ steps.ci-preflight.outputs.local-service-fqdn }}
      service-url: ${{ steps.ci-preflight.outputs.service-url }}
      effective-branch: ${{ steps.ci-preflight.outputs.effective-branch }}

    steps:
      - name: Pre-Flight Checks
        id: ci-preflight
        uses: mdefenders-actions/ci-preflight@dev
        with:
          domain: ${{ vars.DOMAIN }}
          environment: ${{ inputs.deploy-to-environment }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "${{ vars.NODE_VER || '20' }}"
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Run Unit Tests
        uses: mdefenders-actions/ci-code-quality@dev
        with:
          minCoverage: ${{ vars.MIN_COVERAGE }}

      - name: Get Image Tags
        id: get-image-tags
        uses: mdefenders-actions/ci-prepare-docker-build@dev

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ steps.get-image-tags.outputs.new-image }}

      - name: Build and push (optional) Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.get-image-tags.outputs.all-images }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install Trivy Template
        run: |
          mkdir -p contrib
          wget -q -O contrib/html.tpl  ${{ vars.TRIVY_TEMPLATE || 'https://raw.githubusercontent.com/mdefenders/misc/refs/heads/main/aquasecurity/trivy/contrib/html.tpl'}}          

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ steps.get-image-tags.outputs.new-image }}:${{ steps.get-image-tags.outputs.new-tag }}'
          format: 'template'
          template: "@contrib/html.tpl"
          exit-code: ${{ vars.FAIL_BUILDS_ON_SCAN == 'true' && '1' || '0' }}
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-report.html'

      - name: Print Trivy summary
        if: always()
        run: |
          echo '### Trivy scan report:' >> $GITHUB_STEP_SUMMARY
          echo '<details><summary>Click to expand Image Scan Result</summary>' >> $GITHUB_STEP_SUMMARY          
          cat trivy-report.html >> $GITHUB_STEP_SUMMARY
          echo '</details>' >> $GITHUB_STEP_SUMMARY

      - name: Call CD
        id: call-cd
        uses: mdefenders-actions/call-action@dev
        with:
          github-token: ${{ secrets.MDEFENDERS_GITHUB_TOKEN }}
          workflows-to-call: |
            {
              "${{ steps.ci-preflight.outputs.gitops-repo }}": {
                "yaml": "${{ vars.GITOPS_CD_WORKFLOW || 'cd-update-gitops.yaml' }}",
                "ref": "${{ vars.GITOPS_CD_DEFAULT_BRANCH || 'main' }}",
                "data": {
                  "gitops-branch": "${{ steps.ci-preflight.outputs.effective-branch }}",
                  "new-tag": "${{ steps.get-image-tags.outputs.new-tag }}",
                  "gitops-file": "${{ steps.ci-preflight.outputs.gitops-file }}",
                  "image": "${{ steps.get-image-tags.outputs.new-image }}",
                  "app": "${{ steps.ci-preflight.outputs.app-name }}",
                  "replicas": "${{ vars.DEV_TEST_REPLICAS || '3' }}",
                  "rollback": "false",
                  "dry-run": "false"
                }
              }
            }
      - name: Notify and Report on Failure
        if: failure()
        uses: mdefenders-actions/cd-notify-and-report@dev
        with:
          image-name: ${{ steps.get-image-tags.outputs.new-image }}
          image-tag: ${{ steps.get-image-tags.outputs.new-tag }}
          prom-push-token: ${{ secrets.PROM_PUSH_TOKEN }}
          workflow-name: ${{ github.workflow }}
          cicd-slack-webhook: ${{ secrets.CICD_SLACK_WEBHOOK }}
          service-url: ${{ steps.ci-preflight.outputs.service-url }}
          loki-push-url: ${{ vars.LOKI_PUSH_URL }}
          start-time: ${{ steps.ci-preflight.outputs.start-time }}
          workflow-success: '0'
          app-name: ${{ steps.ci-preflight.outputs.app-name }}
          environment: 'dev'

  post-deploy:
    if: startsWith(github.head_ref || github.ref_name, 'feature/') || github.ref_name == 'main '&& github.ref_type == 'branch'
    name: Post-Deploy Workflow
    runs-on: ubuntu-latest
    needs: action-based-ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "${{ vars.NODE_VER || '20' }}"
          cache: npm

      - name: Verify deployment
        uses: mdefenders-actions/cd-verify-deployment@dev
        with:
          expected-pods: ${{ vars.DEV_TEST_REPLICAS || '3' }}
          pull-interval: ${{ vars.DEPLOY_PULL_INTERVAL || '20' }}
          pull-count: ${{ vars.DEPLOY_PULL_COUNT || '10' }}
          force-run-tests: ${{ vars.DEPLOY_FORCE_RUN_TESTS || 'false' }}
          app-name: ${{ needs.action-based-ci.outputs.app-name }}
          revision-tag: ${{ needs.action-based-ci.outputs.new-tag }}
          k8s-namespace: ${{ needs.action-based-ci.outputs.target-namespace }}

      - name: Post-Deploy Tests
        uses: mdefenders-actions/ci-code-quality@dev
        with:
          runLint: false
          runUnitTests: false
          runIntegrationTests: true
          reportTitle: 'Regression Tests'
          appName: ${{ needs.action-based-ci.outputs.app-name }}
          serviceDomain: ${{ vars.DOMAIN || 'svc.cluster.local' }}
          namespace: ${{ needs.action-based-ci.outputs.target-namespace }}
          subdomain: ${{ needs.action-based-ci.outputs.subdomain }}

      - name: Call CD Reduce
        id: call-cd-reduce
        uses: mdefenders-actions/call-action@dev
        with:
          github-token: ${{ secrets.MDEFENDERS_GITHUB_TOKEN }}
          workflows-to-call: |
            {
              "${{ needs.action-based-ci.outputs.gitops-repo }}": {
                "yaml": "${{ vars.GITOPS_CD_WORKFLOW || 'cd-update-gitops.yaml' }}",
                "ref": "${{ vars.GITOPS_CD_DEFAULT_BRANCH || 'main' }}",
                "data": {
                  "gitops-branch": "${{ needs.action-based-ci.outputs.effective-branch }}",
                  "new-tag": "${{ needs.action-based-ci.outputs.new-tag }}",
                  "gitops-file": "${{ needs.action-based-ci.outputs.gitops-file }}",
                  "image": "${{ needs.action-based-ci.outputs.new-image }}",
                  "app": "${{ needs.action-based-ci.outputs.app-name }}",
                  "replicas": "${{ vars.DEV_REPLICAS || '0' }}",
                  "rollback": "false",
                  "dry-run": "false"
                }
              }
            }
      - name: Notify and Report
        if: always()
        uses: mdefenders-actions/cd-notify-and-report@dev
        with:
          image-name: ${{ needs.action-based-ci.outputs.new-image }}
          image-tag: ${{ needs.action-based-ci.outputs.new-tag }}
          prom-push-token: ${{ secrets.PROM_PUSH_TOKEN }}
          workflow-name: ${{ github.workflow }}
          cicd-slack-webhook: ${{ secrets.CICD_SLACK_WEBHOOK }}
          service-url: ${{ needs.action-based-ci.outputs.service-url }}
          loki-push-url: ${{ vars.LOKI_PUSH_URL }}
          start-time: ${{ needs.action-based-ci.outputs.start-time }}
          workflow-success: ${{ job.status == 'success' && '1' || '0' }}
          app-name: ${{ needs.action-based-ci.outputs.app-name }}
          environment: 'dev'
