name: Feature Branch CI

on:
  workflow_call:

jobs:
  call-metrics-init:
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Init Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-init.yaml@dev

  call-code-quality:
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Code Quality Workflow
    uses: mdefenders/shared-workflows/.github/workflows/code-quality.yaml@dev

  call-build-docker:
    needs: call-code-quality
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Build Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/build-docker.yaml@dev
    with:
      push-image: true
    secrets: inherit

  call-scan-docker:
    needs: call-build-docker
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Scan Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/scan-docker.yaml@dev
    with:
      new-tag: ${{ needs.call-build-docker.outputs.new-tag }}
    secrets: inherit

  call-cd-deploy:
    needs: call-build-docker
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Deploy Image Workflow
    uses: mdefenders/shared-workflows/.github/workflows/cd-deploy.yaml@dev
    with:
      new-tag: ${{ needs.call-build-docker.outputs.new-tag }}
      gitops-file: ${{ vars.GITOPS_FILE_PATH || 'deploy/environments' }}/dev/${{ vars.GITOPS_FILE_NAME || 'values.yaml' }}
      environment: 'dev'
      replicas: ${{ fromJSON(vars.DEV_TEST_REPLICAS || '3') }}


  call-metrics-push-success:
    needs: [ call-build-docker, call-scan-docker, call-cd-deploy, call-code-quality, call-metrics-init ]
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'Feature Branch CI'
      workflow-success: 1
    secrets: inherit

  call-metrics-push-failure:
    needs: [ call-build-docker, call-scan-docker, call-cd-deploy, call-code-quality, call-metrics-init ]
    if: failure() && startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'Feature Branch CI'
    secrets: inherit