name: Feature Branch CI

on:
  workflow_call:

jobs:
  call-metrics-init:
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Init Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-init.yaml@dev

  action-based-ci:
    needs: call-metrics-init
    name: Action-Based CI Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Run Action-Based CI
        uses: mdefenders-actions/ci-code-quality@dev
        with:
          minCoverage: ${{ vars.MIN_COVERAGE || '65' }}

  call-build-docker:
    needs: action-based-ci
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Build Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/build-docker.yaml@dev
    with:
      push-image: true
    secrets: inherit

  call-scan-docker:
    needs: call-build-docker
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Scan Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/scan-docker.yaml@dev
    with:
      new-tag: ${{ needs.call-build-docker.outputs.new-tag }}
    secrets: inherit

  call-cd-deploy:
    needs: call-build-docker
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Deploy Image Workflow
    uses: mdefenders/shared-workflows/.github/workflows/cd-deploy.yaml@dev
    with:
      new-tag: ${{ needs.call-build-docker.outputs.new-tag }}
      gitops-file: ${{ vars.GITOPS_FILE_PATH || 'deploy/environments' }}/dev/${{ vars.GITOPS_FILE_NAME || 'values.yaml' }}
      environment: 'dev'
      replicas: ${{ fromJSON(vars.DEV_TEST_REPLICAS || '3') }}

  call-trigger-tests:
    needs: call-cd-deploy
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Trigger Post-Deploy Tests Workflow
    uses: mdefenders/shared-workflows/.github/workflows/trigger-tests.yaml@dev
    with:
      new-tag: ${{ needs.call-cd-deploy.outputs.new-tag }}
      current-tag: ${{ needs.call-cd-deploy.outputs.current-tag }}
      environment: 'dev'
    secrets: inherit

  call-cd-undeploy:
    needs: [ call-cd-deploy, call-trigger-tests ]
    if: always() && startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Deploy Image Workflow
    uses: mdefenders/shared-workflows/.github/workflows/cd-deploy.yaml@dev
    with:
      new-tag: ${{ needs.call-trigger-tests.outputs.new-tag }}
      gitops-file: ${{ vars.GITOPS_FILE_PATH || 'deploy/environments' }}/dev/${{ vars.GITOPS_FILE_NAME || 'values.yaml' }}
      environment: 'dev'
      replicas: ${{ fromJSON(vars.DEV_REPLICAS || '0') }}

  call-metrics-push-success:
    needs: [ call-build-docker, call-scan-docker, call-cd-deploy, call-cd-undeploy, call-trigger-tests, action-based-ci, call-metrics-init ]
    if: startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'Feature Branch CI'
      workflow-success: 1
    secrets: inherit

  call-metrics-push-failure:
    needs: [ call-build-docker, call-scan-docker, call-cd-deploy, call-cd-undeploy, call-trigger-tests, action-based-ci, call-metrics-init ]
    if: failure() && startsWith(github.head_ref || github.ref_name, 'feature/') && github.ref_type == 'branch'
    name: Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'Feature Branch CI'
    secrets: inherit