name: Feature Branch CI

on:
  workflow_call:

jobs:
  call-pre-flight:
    if: startsWith(github.ref, 'refs/heads/feature/')
    name: Call Pre- Flight Workflow
    uses: mdefenders/shared-workflows/.github/workflows/code-quality.yaml@dev
  call-code-quality:
    if: startsWith(github.ref, 'refs/heads/feature/')
    name: Call Code Quality Workflow
    uses: mdefenders/shared-workflows/.github/workflows/code-quality.yaml@dev

#  call-build-docker:
#    if: startsWith(github.ref, 'refs/heads/feature/')
#    name: Call Build Docker Workflow
#    uses: mdefenders/shared-workflows/.github/workflows/build-docker.yaml@dev
#    with:
#      dry-run: true
#    secrets: inherit