name: Logs Push Workflow

on:
  workflow_call:
    inputs:
      start-time:
        type: string
      workflow-name:
        type: string
      workflow-success:
        type: string
        default: 0
    secrets:
      PROM_PUSH_USER:
        required: true
      PROM_PUSH_TOKEN:
        required: true

jobs:
  metrics-push:
    name: Push Logs to Loki
    runs-on: ubuntu-latest
    steps:
      - name:  Push Logs to Loki
        run: |
          METRIC_TIMESTAMP=$(date +%s)
          LOG_TIMESTAMP=$(date +%s%N)
          DURATION=$(($METRIC_TIMESTAMP - ${{ inputs.start-time }}))
          LOG_ENTRY="run_id=${GITHUB_RUN_ID} name=${{ inputs.workflow-name }} duration=$DURATION"s
          if [[ -z "${{ inputs.start-time }}" ]]; then
            RUN_STATUS="failure"
          else
            if [[ "${{ inputs.workflow-success }}" == '0' ]]; then
              RUN_STATUS="failure"
              LOG_ENTRY="${LOG_ENTRY} status=failure"
            else
              RUN_STATUS="success"
              LOG_ENTRY="${LOG_ENTRY} status=success"          
            fi        
          fi
          curl -ks -X POST ${{ vars.LOKI_PUSH_URL }} \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic ${{ secrets.PROM_PUSH_TOKEN }}" \
            -d "{\"streams\": [{\"stream\": {\"service\": \"${GITHUB_REPOSITORY}\",\"name\": \"${{ inputs.workflow-name }}\", \
            \"status\": \"${RUN_STATUS}\"},\"values\": [[\"$LOG_TIMESTAMP\", \"$LOG_ENTRY\"]]}]}"
          
