name: Pre-flight Checks

on:
  workflow_call:

jobs:
  pre-flight:
    name: Pre-flight Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup the build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v4