name: PreProd Branch CI

on:
  workflow_call:

jobs:
  call-metrics-init:
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Init Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-init.yaml@dev

  call-code-quality:
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Code Quality Workflow
    uses: mdefenders/shared-workflows/.github/workflows/code-quality.yaml@dev

  call-build-docker:
    needs: call-code-quality
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Build Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/build-docker.yaml@dev
    with:
      push-image: ${{ fromJSON(vars.PUSH_STAGING_IMAGE || 'true') }}
    secrets: inherit

  call-scan-docker:
    needs: call-build-docker
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Scan Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/scan-docker.yaml@dev
    with:
      new-tag: ${{ needs.call-build-docker.outputs.new-tag }}
    secrets: inherit

  call-cd-deploy:
    needs: call-build-docker
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Deploy Image Workflow
    uses: mdefenders/shared-workflows/.github/workflows/cd-deploy.yaml@dev
    with:
      new-tag: ${{ needs.call-build-docker.outputs.new-tag }}
      gitops-file: ${{ vars.GITOPS_FILE_PATH || 'deploy/environments' }}/preprod/${{ vars.GITOPS_FILE_NAME || 'values.yaml' }}
      environment: 'preprod'

  call-trigger-tests:
    needs: call-build-docker
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Trigger Post-Deploy Tests Workflow
    uses: mdefenders/shared-workflows/.github/workflows/trigger-tests.yaml@dev
    with:
      new-tag: ${{ needs.call-build-docker.outputs.new-tag }}
      current-tag: ${{ needs.call-build-docker.outputs.new-tag }}
      environment: 'preprod'
    secrets: inherit

  call-metrics-push-success:
    needs: [ call-build-docker, call-scan-docker, call-cd-deploy, call-trigger-tests, call-code-quality, call-metrics-init ]
    if: ${{ startsWith(github.head_ref || github.ref_name, 'main') }}
    name: Call Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'PreProd Branch CI'
      workflow-success: 1
    secrets: inherit

  call-metrics-push-failure:
    needs: [ call-build-docker, call-scan-docker, call-cd-deploy, call-trigger-tests, call-code-quality, call-metrics-init ]
    if: ${{ failure() && startsWith(github.head_ref || github.ref_name, 'main') }}
    name: Call Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'PreProd Branch CI'
    secrets: inherit