name: PreProd Branch CI

on:
  workflow_call:

jobs:
  call-get-tag:
    - name: Get latest tag
      id: get-latest-tag
      uses: actions-ecosystem/action-get-latest-tag@v1

    - name: Print latest tag
      run: echo "Latest tag is ${{ steps.get-latest-tag.outputs.tag }}"

#  call-cd-deploy:
#    if: startsWith(github.head_ref || github.ref_name, 'main')
#    name: Call Deploy Image Workflow
#    uses: mdefenders/shared-workflows/.github/workflows/cd-deploy.yaml@dev
#    with:
#      link-tag: ${{ needs.call-get-tag.outputs.link-tag }}
#      gitops-file: ${{ vars.GITOPS_FILE_PATH || 'deploy/environments' }}/prod/${{ vars.GITOPS_FILE_NAME || 'values.yaml' }}
#      environment: 'prod'
#
#  call-trigger-tests:
#    needs: call-cd-deploy
#    if: startsWith(github.head_ref || github.ref_name, 'main')
#    name: Call Trigger Post-Deploy Tests Workflow
#    uses: mdefenders/shared-workflows/.github/workflows/trigger-tests.yaml@dev
#    with:
#      link-tag: ${{ needs.call-build-docker.outputs.link-tag }}
#      environment: 'prod'