name: Promote to Prod

on:
  workflow_call:

jobs:
  call-metrics-init:
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Init Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-init.yaml@dev

  call-get-tag:
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Check Release Branch
    runs-on: ubuntu-latest
    outputs:
      link-tag: ${{ steps.get-tag.outputs.link-tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate SemVer Format
        id: get-tag
        run: |
          git fetch origin main --tags

          LATEST_TAG=$(git tag -l | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)

          if [[ -z "$LATEST_TAG" ]]; then
            echo "No SemVer tags found"
            exit 1
          fi
          TAG_COMMIT=$(git rev-list -n 1 "$LATEST_TAG")
          if ! git merge-base --is-ancestor "$TAG_COMMIT" origin/main; then
            echo "Tag $LATEST_TAG is NOT from main branch"
            exit 1
          fi
          echo "Latest SemVer tag: $LATEST_TAG"
          echo "link-tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "LINK_TAG=$LATEST_TAG" >> "$GITHUB_ENV"


      - name: Check if Docker image exists on DockerHub
        id: check-image
        uses: tyriis/docker-image-tag-exists@v2.1.0
        with:
          registry: docker.io
          repository: ${{ github.repository }}
          tag: ${{ env.LINK_TAG }}

      - name: Exit if image not found
        if: steps.check-image.outputs.tag == 'not found'
        run: |
          echo "Docker image ${{ github.repository }}:${{ env.LINK_TAG }} not found . Exiting."
          exit 1

  call-scan-docker:
    needs: call-get-tag
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Scan Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/scan-docker.yaml@dev
    with:
      link-tag: ${{ needs.call-get-tag.outputs.link-tag }}
    secrets: inherit

  call-cd-deploy:
    needs: call-scan-docker
    if: startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Deploy Image Workflow
    uses: mdefenders/shared-workflows/.github/workflows/cd-deploy.yaml@dev
    with:
      link-tag: ${{ needs.call-get-tag.outputs.link-tag }}
      gitops-file: ${{ vars.GITOPS_FILE_PATH || 'deploy/environments' }}/prod/${{ vars.GITOPS_FILE_NAME || 'values.yaml' }}
      environment: 'prod'

  call-trigger-tests:
    needs: call-cd-deploy
    if: startsWith(github.head_ref || github.ref_name, 'main') && needs.call-cd-deploy.outputs.current-tag != needs.call-get-tag.outputs.link-tag
    name: Call Trigger Post-Deploy Tests Workflow
    uses: mdefenders/shared-workflows/.github/workflows/trigger-tests.yaml@dev
    with:
      link-tag: ${{ needs.call-get-tag.outputs.link-tag }}
      current-tag: ${{ needs.call-cd-deploy.outputs.current-tag }}
      environment: 'prod'
    secrets: inherit

  rollback-cd-deploy:
    needs: call-trigger-tests
    if: failure() && startsWith(github.head_ref || github.ref_name, 'main')
    name: Call Rollback Deploy Image Workflow
    uses: mdefenders/shared-workflows/.github/workflows/cd-deploy.yaml@dev
    with:
      link-tag: ${{ needs.call-trigger-tests.outputs.current-tag }}
      gitops-file: ${{ vars.GITOPS_FILE_PATH || 'deploy/environments' }}/prod/${{ vars.GITOPS_FILE_NAME || 'values.yaml' }}
      environment: 'prod'
    secrets: inherit

  call-metrics-push-success:
    needs: [ call-scan-docker, call-get-tag, call-cd-deploy, call-trigger-tests, call-metrics-init ]
    if: ${{ startsWith(github.head_ref || github.ref_name, 'main') }}
    name: Call Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'Promote to Prod'
      workflow-success: 1
    secrets: inherit

  call-metrics-push-failure:
    needs: [ call-scan-docker, call-get-tag, call-cd-deploy, call-trigger-tests, call-metrics-init ]
    if: ${{ failure() && startsWith(github.head_ref || github.ref_name, 'main') }}
    name: Call Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'Promote to Prod'
    secrets: inherit