name: Promote to Prod

on:
  workflow_call:

jobs:
  action-based-promote:
    if: github.ref_name == 'main' && github.ref_type == 'branch'
    name: Action-Based Promotion Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Pre-Flight Checks
        id: ci-preflight
        uses: mdefenders-actions/ci-preflight@dev
        with:
          domain: ${{ vars.DOMAIN }}
          environment: 'prod'
