name: Publish Docker Image

on:
  workflow_call:
    inputs:
      build-args:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, docker-runner]
    steps:
      - name: Cleanup the build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set tag env
        run: |
          echo "DOCKERHUB_REPO=$GITHUB_REPOSITORY" >> $GITHUB_ENV
          
          if [[ $GITHUB_REF_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Release tag found"
            echo "TAGS=$GITHUB_REPOSITORY:latest,$GITHUB_REPOSITORY:$GITHUB_REF_NAME" >> $GITHUB_ENV
            echo "IMAGE_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
          else
            echo "Feature tag/branch found"
            echo "TAGS=$GITHUB_REPOSITORY:$GITHUB_REF_NAME.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
            echo "IMAGE_TAG=$GITHUB_REF_NAME.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.DOCKERHUB_REPO }}

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}

      - name: Print summary
        run: |
          echo '### The image built:' >> $GITHUB_STEP_SUMMARY
          echo '['${{ env.DOCKERHUB_REPO }}':'${{ env.IMAGE_TAG }}'](https://hub.docker.com/layers/'${{ env.DOCKERHUB_REPO }}'/'${{ env.IMAGE_TAG }}'/images/'${{ steps.build_and_push.outputs.digest }}')' >> $GITHUB_STEP_SUMMARY