name: Release Branch CI

on:
  workflow_call:

jobs:
  call-code-quality:
    name: Call Code Quality Workflow
    uses: mdefenders/shared-workflows/.github/workflows/code-quality.yaml@dev

  call-build-docker:
    needs: call-code-quality
    if: startsWith(github.ref, 'refs/heads/release/')
    name: Call Build Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/build-docker.yaml@dev
    with:
      push-image: ${{ fromJSON(vars.PUSH_PR_IMAGE || 'true') }}
    secrets: inherit

  call-scan-docker:
    needs: call-build-docker
    if: startsWith(github.ref, 'refs/heads/release/')
    name: Call Scan Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/scan-docker.yaml@dev
    with:
      link-tag: ${{ needs.call-build-docker.outputs.link-tag }}
    secrets: inherit