name: Release/Hotfix Branch PR CI

on:
  workflow_call:

jobs:
  check-release-branch:
    if: (startsWith(github.head_ref || github.ref_name, 'release/') || startsWith(github.head_ref || github.ref_name, 'hotfix/'))
    name: Check Release/Hotfix  Branch
    runs-on: ubuntu-latest
    steps:
      - name: Validate SemVer Format
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Validating branch: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^(release|hotfix)\/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Branch name must follow release|hotfix/x.y.z (SemVer) format"
            exit 1
          fi

  call-metrics-init:
    if: (startsWith(github.head_ref || github.ref_name, 'release/') || startsWith(github.head_ref || github.ref_name, 'hotfix/'))
    name: Call Init Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-init.yaml@dev

  call-code-quality:
    needs: check-release-branch
    if: (startsWith(github.head_ref || github.ref_name, 'release/') || startsWith(github.head_ref || github.ref_name, 'hotfix/'))
    name: Call Code Quality Workflow
    uses: mdefenders/shared-workflows/.github/workflows/code-quality.yaml@dev

  call-build-docker:
    needs: call-code-quality
    if: (startsWith(github.head_ref || github.ref_name, 'release/') || startsWith(github.head_ref || github.ref_name, 'hotfix/'))
    name: Call Build Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/build-docker.yaml@dev
    with:
      push-image: ${{ fromJSON(vars.PUSH_PR_IMAGE || 'true') }}
    secrets: inherit

  call-scan-docker:
    needs: call-build-docker
    if: (startsWith(github.head_ref || github.ref_name, 'release/') || startsWith(github.head_ref || github.ref_name, 'hotfix/'))
    name: Call Scan Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/scan-docker.yaml@dev
    with:
      new-tag: ${{ needs.call-build-docker.outputs.new-tag }}
    secrets: inherit

  call-trigger-tests:
    needs: call-build-docker
    if: (startsWith(github.head_ref || github.ref_name, 'release/') || startsWith(github.head_ref || github.ref_name, 'hotfix/'))
    name: Call Trigger Post-Deploy Tests Workflow
    uses: mdefenders/shared-workflows/.github/workflows/trigger-tests.yaml@dev
    with:
      new-tag: ${{ needs.call-build-docker.outputs.new-tag }}
      current-tag: ${{ needs.call-build-docker.outputs.new-tag }}
      environment: 'staging'
    secrets: inherit

  call-metrics-push-success:
    needs: [ check-release-branch, call-build-docker, call-scan-docker, call-trigger-tests, call-code-quality, call-metrics-init ]
    if: (startsWith(github.head_ref || github.ref_name, 'release/') || startsWith(github.head_ref || github.ref_name, 'hotfix/'))
    name: Call Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'Release/Hotfix Branch PR CI'
      workflow-success: 1
    secrets: inherit

  call-metrics-push-failure:
    needs: [ check-release-branch, call-build-docker, call-scan-docker, call-trigger-tests, call-code-quality, call-metrics-init ]
    if: failure() && (startsWith(github.head_ref || github.ref_name, 'release/') || startsWith(github.head_ref || github.ref_name, 'hotfix/'))
    name: Call Push Metrics Workflow
    uses: mdefenders/shared-workflows/.github/workflows/metrics-push.yaml@dev
    with:
      start-time: ${{ needs.call-metrics-init.outputs.start-time }}
      workflow-name: 'Release/Hotfix Branch PR CI'
    secrets: inherit