name: Release/Hotfix Branch PR CI

on:
  workflow_call:

jobs:
  check-release-branch:
    if: startsWith(github.head_ref || github.ref_name, 'release/' || github.ref_name, 'hotfix/')
    name: Check Release/Hotfix  Branch
    runs-on: ubuntu-latest
    steps:
      - name: Validate SemVer Format
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Validating branch: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^(release|hotfix)\/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Branch name must follow release|hotfix/x.y.z (SemVer) format"
            exit 1
          fi

  call-code-quality:
    needs: check-release-branch
    if: startsWith(github.head_ref || github.ref_name, 'release/' || github.ref_name, 'hotfix/')
    name: Call Code Quality Workflow
    uses: mdefenders/shared-workflows/.github/workflows/code-quality.yaml@dev


  call-build-docker:
    needs: call-code-quality
    if: startsWith(github.head_ref || github.ref_name, 'release/' || github.ref_name, 'hotfix/')
    name: Call Build Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/build-docker.yaml@dev
    with:
      push-image: ${{ fromJSON(vars.PUSH_PR_IMAGE || 'true') }}
    secrets: inherit

  call-scan-docker:
    needs: call-build-docker
    if: startsWith(github.head_ref || github.ref_name, 'release/' || github.ref_name, 'hotfix/')
    name: Call Scan Docker Workflow
    uses: mdefenders/shared-workflows/.github/workflows/scan-docker.yaml@dev
    with:
      link-tag: ${{ needs.call-build-docker.outputs.link-tag }}
    secrets: inherit

  call-trigger-tests:
    needs: call-build-docker
    if: startsWith(github.head_ref || github.ref_name, 'release/' || github.ref_name, 'hotfix/')
    name: Call Trigger Post-Deploy Tests Workflow
    uses: mdefenders/shared-workflows/.github/workflows/trigger-tests.yaml@dev
    with:
      link-tag: ${{ needs.call-build-docker.outputs.link-tag }}
      current-tag: ${{ needs.call-build-docker.outputs.link-tag }}
      environment: 'staging'