name: Scan Docker Image

on:
  workflow_call:
    inputs:
      link-tag:
        type: string
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true

jobs:
  pull_and_scan:
    name: Pull and scan Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.64.1/trivy_0.64.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.64.1_Linux-64bit.deb

      - name: Pull image
        run: docker pull '${{ inputs.link-tag }}'

      - name: Run Trivy
        run: trivy image --exit-code 1 --severity CRITICAL,HIGH '${{ inputs.link-tag }}'

#      - name: Print summary
#        run: |
#          echo '### The image repo tags:' >> $GITHUB_STEP_SUMMARY
#          echo '['${{ env.DOCKERHUB_REPO }}'](https://hub.docker.com/repository/docker/'${{ env.DOCKERHUB_REPO }}'/tags/)' >> $GITHUB_STEP_SUMMARY
#          echo '### The built image content:' >> $GITHUB_STEP_SUMMARY
#          echo '['${{ env.DOCKERHUB_REPO }}':'${{ env.LINK_TAG }}'](https://hub.docker.com/layers/'${{ env.DOCKERHUB_REPO }}'/'${{ env.LINK_TAG }}'/images/'${{ steps.build_and_push.outputs.digest }}')' >> $GITHUB_STEP_SUMMARY
#
