name: Scan Docker Image

on:
  workflow_call:
    inputs:
      new-tag:
        type: string
        required: true
      new-image:
        type: string
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true

jobs:
  pull-and-scan:
    name: Pull and scan Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Trivy Template
        run: |
          mkdir -p contrib
          wget -q -O contrib/html.tpl  ${{ vars.TRIVY_TEMPLATE || 'https://raw.githubusercontent.com/mdefenders/misc/refs/heads/main/aquasecurity/trivy/contrib/html.tpl'}}          

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ inputs.new-image }}:${{ inputs.new-tag }}'
          format: 'template'
          template: "@contrib/html.tpl"
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-report.html'

      - name: Print Trivy summary
        if: always()
        run: |
          echo '### Trivy scan report:' >> $GITHUB_STEP_SUMMARY
          echo '<details><summary>Click to expand Image Scan Result</summary>' >> $GITHUB_STEP_SUMMARY          
          cat trivy-report.html >> $GITHUB_STEP_SUMMARY
          echo '</details>' >> $GITHUB_STEP_SUMMARY